### ISSUE TITLE
Formatting problem for DataContext value.

### ISSUE THREAD

**Issue by philipag** [NicoVermeir/XamlStyler#12]
The following is the result I get.  Nothing I do seems to be able to get DataContext to occupy only one line.  Just in case I added it to "Elements no line break between attributes".  I also tried making the line shorter than the others.

<UserControl x:Class="ThoughtDSP.View.xxxxxx"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:telerik3="http://schemas.telerik.com/2008/xaml/presentation"
             DataContext="{Binding XXXXXVm,
                                   Source={StaticResource Locator}}"
             d:DesignHeight="600"
             d:DesignWidth="906"

**Comment by NicoVermeir** [comment]
added the following options:
- keep Binding on same line (default: false)
- keep x:Bind on same line (default: true)
