### ISSUE TITLE
Is there a way to disable ordering of attributes for an element?

### ISSUE THREAD

**Issue by JohanLarsson** [NicoVermeir/XamlStyler#21]
I was writing a control template with a bunch of template bindings and thought it made sense to group them per baseclass level. I had an empty line between each group.
[code](https://github.com/JohanLarsson/Gu.Wpf.NumericInput/blob/master/Gu.Wpf.NumericInput/Themes/Generic.xaml#L109).

Ctrl+2 orderded them by name which is great most times but I felt like I wanted to disable it for this instance.

Really nice tool!
Why do you use regions in the C# code?

**Comment by NicoVermeir** [comment]
added in code, update will be out soon
