### ISSUE TITLE
Feature request: line breaks matching sort groups

### ISSUE THREAD

**Issue by jv42** [NicoVermeir/XamlStyler#22]
Currently, I find the sorting of attributes very useful, but I can't find a satisfying settings combination for the line breaks logic (not even completely disabling it, which could be an interesting addition).

Here's a proposition of a new line break policy, which {c|w}ould be combined with the character/attribute count limits : break on ordering group end.

For instance:

    <TextBlock 
        x:Name="tbDescription"
        Grid.Row="1" Grid.Column="2"
        MaxWidth="200" Height="32" Margin="10,5"
        HorizontalAlignment="Left" VerticalAlignment="Center"
    />

Note: example is not using default configuration, to get exactly this, you would need something like:
 - Max attribute number per line = 5 (or 0)
 - Position first attribute on same line as start tag = false
 - Put ending bracket on new line = true

**Comment by NicoVermeir** [comment]
fixed in 1.5
