### ISSUE TITLE
Feature request: separate line break rules for root element

### ISSUE THREAD

**Issue by jv42** [NicoVermeir/XamlStyler#23]
Currently, in my manual informal XAML coding guideline, I use different rules for the root element (ie UserControl, Window, etc...) and content. I have the required class attribute and all the namespaces on a single line each for instance, which I cannot get with current settings of XAML Styler.

So, I'd love an option to define line breaking separate rules for the root element.

I realize typing this that having a specific option to put no more than one namespace per line whatever the max attribute per line and max character per line would also solve my issue.

**Comment by PolarbearDK** [comment]
I agree that root element should have separate style. 

I have attribute tolerance set to 4, so root nodes with less than 4 attributes are on one line.
I would prefer to always have linebreaks between attributes on root element.

**Comment by PolarbearDK** [comment]
I have made a pull request with that feature.

**Comment by NicoVermeir** [comment]
I'll have a look probably tomorrow evening.
thanks for contributing!

**Comment by jv42** [comment]
@PolarbearDK That's awesome, thanks!

**Comment by NicoVermeir** [comment]
PR merged and Xaml styler 1.4.1 pushed to VS gallery
