### ISSUE TITLE
XamlStyler and VS Express editions

### ISSUE THREAD

**Issue by DansDadUK** [NicoVermeir/XamlStyler#24]
XamlStyler won't install with Visual Studio (2013) Express edition.

Is this because VS Express editions lack the features necessary to add extension packages, or due to some restriction within the XamlStyler package?

[I'm an OAP, and can't justify the cost of a VS Pro licence to enable me to write occasional code].

**Comment by NicoVermeir** [comment]
that is indeed due to the limitation of express edition.
it should work in the new (and free) Visual Studio community edition
