### ISSUE TITLE
Content of element is changed when using encoded unicode

### ISSUE THREAD

**Issue by PolarbearDK** [NicoVermeir/XamlStyler#25]
Element:

`<TextBlock Text="&#xE082;" FontFamily="/Fonts/#Glyphicons Halflings Regular" />`

Is Reformatted as:
`<TextBlock Text="" FontFamily="/Fonts/#Glyphicons Halflings Regular" />`

The content should be preserved "as is".

**Comment by NicoVermeir** [comment]
I'm not seeing any elements in your comment?

**Comment by PolarbearDK** [comment]
...markdown...

How about now?

**Comment by NicoVermeir** [comment]
that's better :)
i'll have a look when I find some time (unless someone else picks it up and sends a PR first ;))

**Comment by PolarbearDK** [comment]
I had a look at it, and found the problem.
 XDocument.Parse is used to load the xaml source before it is escaped. I have a fix ready for that.

However, half of the unit tests were broken. Expected and actual files doesn't match. Do you have versions that pass?

**Comment by NicoVermeir** [comment]
yeah I know about those unit tests, it's somewhere on my backlog to fix them. (I think if I dive into git history and return them to the Original version they should work)

**Comment by PolarbearDK** [comment]
I have fixed both and made a pull request.

**Comment by NicoVermeir** [comment]
I noticed, thanks! I'll have a look on Monday and release a new version

**Comment by NicoVermeir** [comment]
PR accepted, implemening a few other things. updated version will be released this week

thanks for the help!
