### ISSUE TITLE
Wrong indent when "Position first attribute on same line as start tag" is False

### ISSUE THREAD

**Issue by merken** [NicoVermeir/XamlStyler#27]
The formatting results in a lot of spaces in binding expressions.

Consider the following xaml with this option to True :

![image](https://cloud.githubusercontent.com/assets/187081/5679886/e1d1be14-9805-11e4-8e5d-632d8c44ecc4.png)

Now the same xaml with the option to False :

![image](https://cloud.githubusercontent.com/assets/187081/5679930/7dc82722-9806-11e4-9c38-cf9807dd8b76.png)

This is probably because you use the first indented attribute as a baseline for the other attributes ?

**Comment by NicoVermeir** [comment]
fixed in 1.6
