### ISSUE TITLE
Empty tag

### ISSUE THREAD

**Issue by sm-g** [NicoVermeir/XamlStyler#30]
Styler can not work with such xaml:
```xaml
<Label> </Label>
```

**Comment by NicoVermeir** [comment]
that's by design. an empty tag has no use what so ever so it gets removed (unless you can give me a valid reason for empty tags of course :) )

**Comment by sm-g** [comment]
It's not removed, there is "startIndex must be less than length of string" error

Empty tag may have style and so have meaning

**Comment by PolarbearDK** [comment]
I am not able to reproduce this.

sm-g: Could you provide a document that triggers this problem, and also a screen print of where you get the exception.

**Comment by sm-g** [comment]
Seems it was fixed somewhere between 1.4.2 and 1.5.
