### ISSUE TITLE
Property elements cannot be in the middle of an element's content. They must be before or after the content.

### ISSUE THREAD

**Issue by PedroLamas** [NicoVermeir/XamlStyler#33]
The title is an error message I'm currently getting when I use XamlStyler and save a SplitPage: it will order stuff around putting it like "content | properties | content" when it should just be "properties | content"

**Comment by PolarbearDK** [comment]
Could you please provide the "Before" and "After" XAML?

**Comment by NicoVermeir** [comment]
there's a pull request waiting from Pedro that should fix this. Haven't had the time to look at it yet, will try to do so tonight

**Comment by PedroLamas** [comment]
@PolarbearDK if you just create the SplitPage and save it, you will see the error; the pull request I have submitted will fix this and hopefully, not break anything else! :)
