### ISSUE TITLE
Reorder Setter Tags?

### ISSUE THREAD

**Issue by PolarbearDK** [NicoVermeir/XamlStyler#35]
Would it make sense to reorder/sort "Setter" tags on Target/Property, or are there cases where the order of the tags are significant?

**Comment by NicoVermeir** [comment]
hmm haven't encountered any yet. maybe add it as an option and disable it as default?

**Comment by PolarbearDK** [comment]
See pull request #45

**Comment by NicoVermeir** [comment]
fixed in 1.5
