### ISSUE TITLE
Binding arguments are too indented

### ISSUE THREAD

**Issue by RandomEngy** [NicoVermeir/XamlStyler#36]
When you specify a Converter or ConverterParameter on a Binding, it breaks them onto a newline and gives them a crazy amount of indentation. Can you reduce the indentation or make it configurable in some way?

**Comment by NicoVermeir** [comment]
is this the same as issue #27 ? if not, could you provide a sample?

**Comment by RandomEngy** [comment]
Ahh you're right it is the same one.
