### ISSUE TITLE
Option for commas vs spaces for Margins and Padding?

### ISSUE THREAD

**Issue by RandomEngy** [NicoVermeir/XamlStyler#37]
Some properties like Margin and Padding allow you to separate numbers by commas or spaces. Can we have an option to automatically switch to one or the other (or leave them alone, like it does now)?

**Comment by PolarbearDK** [comment]
Hmmm tricky. 
How to detect if a property is a Thickness... It could be "hiding" in the value of a setter or in a resource.

Scanning all attributes values and text nodes for the patterns:
(number)(separator)(number)(separator)(number)(separator)(number)  
or 
(number)(separator)(number)
is a possibility, but it might lead to changing something that is not actually a Thickness.

**Comment by RandomEngy** [comment]
I wrote a script that did this and my approach was to have a list of properties that are "whitelisted" for conversion like Margin, Padding and BorderThickness. If you're trawling through the XML document you could detect properties in the normal way but also if you have a <Setter> element with Property="Margin" and edit the Value. Or if you had an <x:Thickness> resource. Of course this doesn't work if the user had created their own property named one of these things that wasn't a Thickness.

But it worked for my purposes.

**Comment by PolarbearDK** [comment]
I'm implementing this right now.

What properties were in your whitelist?

I scanned Presentation* assemblies for references, but ended up with a surprisingly short list:
```
Margin, Padding, BorderThickness, ThumbnailClipMargin
```

**Comment by RandomEngy** [comment]
Awesome! Margin, Padding and BorderThickness were the only ones I had in my script. I think you could possibly include System.Point as well, and the only ones I know offhand that use that are RenderTransformOrigin, StartPoint and EndPoint.

**Comment by PolarbearDK** [comment]
I have made a beta release available at: 
https://github.com/PolarbearDK/XamlStyler/releases/tag/2.0Beta

I have not included your suggestion for System.Point, but if you configure the suggested properties in "Thickness attributes" it should work.

**Comment by RandomEngy** [comment]
Nice! I just tested it out and it seems to work for me.

**Comment by pfattisc** [comment]
+1
