### ISSUE TITLE
Feature request: Support XAML Regions

### ISSUE THREAD

**Issue by soeron** [NicoVermeir/XamlStyler#39]
Greetings,

Recently installed this VS extension https://visualstudiogallery.msdn.microsoft.com/3c534623-bb05-417f-afc0-c9e26bf0e177 (XAML Regions).
After save (and beautify) the closing tag is moved few elements down (reorders its position).
Before save:
```XAML
<ParentElement>
    <!-- Region RegionName -->
    <ChildElement />
    <ChildElement />
    <ChildElement />
    <ChildElement />
    <!-- EndRegion -->
    <ChildElement />
</ParentElement>
```
After save:
```XAML
<ParentElement>
    <!-- Region RegionName -->
    <ChildElement />
    <ChildElement />
    <ChildElement />
    <ChildElement />
    <ChildElement />
    <!-- EndRegion -->
</ParentElement>
```

Also noticed something annoying:
When the option "Beautify on save" is selected and when the file is saved all the collapsed elements are being expanded. Even if there are no changes to the file. Is there a fix for this or I will have to live with it?

Best Regards,
Daniel Tsviatkov

**Comment by NicoVermeir** [comment]
hmm I'm not seeing this issue without the xaml regions plugin installed. I'll need to look into that.

concerning the collapsed elements, I'm afraid that due to the way xaml styler works it won't be possible to keep them collapsed

**Comment by yangmijun** [comment]
Found same issure. Using XAML Regions plugin, the closing tag "" is moved after s save.

**Comment by NicoVermeir** [comment]
does this still happen if you disable the reordering of Grid children?

**Comment by PolarbearDK** [comment]
If parent element is Grid or Canvas, then this might be related to #47

**Comment by yangmijun** [comment]
After I disable the reordering of Grid children, the problem seems disappeared.

**Comment by riwickel** [comment]
fixed in https://github.com/NicoVermeir/XamlStyler/pull/81
