### ISSUE TITLE
No Attribute Reordering With "Order attributes by name" Turned Off

### ISSUE THREAD

**Issue by tstotis** [NicoVermeir/XamlStyler#40]
Setting the new "#10 Order attributes by name" setting to False does not reorder any of the attributes at all, including attributes that are included in the other Rule Groups.

I've included a screenshot of my settings, in case there's something else there you need to reproduce this issue. As you see it in that screenshot, formatting XAML will not reorder any attributes. Setting "10 Order attributes by name" to True will properly reorder all of the attributes as defined by the rule groups, and then sort the rest of them alphabetically, as expected.

![xamlstylersettings](https://cloud.githubusercontent.com/assets/10945523/6132966/9c766d1e-b124-11e4-9470-9de89f2c08a4.png)

**Comment by PolarbearDK** [comment]
You are absolutely right! 

That setting is really badly labeled as what it does is disable all attribute reordering.

I have a Work-In-Progress change that redesigns the settings page. It has two separate properties:
- "Enable Attribute reordering" 
- "Order attributes by name"

**Comment by PolarbearDK** [comment]
I have made a beta release available at: 
https://github.com/PolarbearDK/XamlStyler/releases/tag/2.0Beta
