### ISSUE TITLE
Feature request: Remember collapsed sections

### ISSUE THREAD

**Issue by wiggisser** [NicoVermeir/XamlStyler#41]
I often collapse sections in my xaml when I don't currently work on them, but everytime i save the layout, all sections are expanded again. It would be nice if sections which were collapsed before reformatting would stay collapsed afterwards.

**Comment by NicoVermeir** [comment]
this isn't possible with how xamlstyler is currently setup to work. the tool pulls in your entire xaml code, reformats it in memory, clears your xaml file and writes the in memory code into the file. (also, same problem reported in #39 )
