### ISSUE TITLE
Option for using tabs instead of spaces

### ISSUE THREAD

**Issue by jmichas** [NicoVermeir/XamlStyler#42]
I have my VS options set to use tabs, when I save using XamlStyler I think it uses spaces so then I get the header bar popping up asking me if I want to tabbify it. If I select yes and save, the loop continues since the styler puts in spaces somewhere.

**Comment by PolarbearDK** [comment]
Xaml Styler uses the tab settings defined for Visual Studios Xaml editor.

See:
Tools -> Options -> Text Editor -> Xaml -> Tabs

**Comment by jmichas** [comment]
Ok, yeah, mine is set to use tabs, but I still get the message that I have mixed tabs and spaces after I save. I think the problem is that when attributes in a tag a put on a new line and indented they are indented using spaces not tabs. When I click the tabify button they are converted to tabs and then when I save they are converted back to spaces.

**Comment by PolarbearDK** [comment]
Please try to understand what XamlStyler does to format an Element with attributes on separate lines like this:

```xml
	<TextBlock Style="{StaticResource Hello}"
	           Width="100"
	           Height="100"
	           Text="Hello" />
```

The TextBlock line is indented by one TAB (in you use tabs).
The attribute lines are also indented by a TAB, but then XamlStyler uses spaces to ensure that the attribute lines up with the attributes on previous lines.

You can check it out by displaying tabs + spaces in your editor.
For Visual Studio 2013 use CTRL+E, S to show tabs + spaces.

**Comment by jmichas** [comment]
Ok, I see the issue now. I have Productivity Power Tools installed. By default that has "Fix Mixed Tabs" enabled. I guess I've had that setup for a long time because I always tabify my code. So when I save, the Xaml Styler does what you described and then the PPT barks at me with a notice bar telling me "you have mixed tabs and spaces, do you want to tabify?". I turned off the fix mixed tabs setting and now all is well, but I think it would be nice to have a Xaml Styler option to use tabs instead of spaces for the attribute indenting so that we can use the PPT setting to enforce tabs in other code files.

Thanks for your time.

**Comment by NicoVermeir** [comment]
whoops, hit the close button a bit too fast :)
not added in latest version, but I'll keep the issue open

**Comment by PolarbearDK** [comment]
I think this can be closed. Can be configured using Xaml editor settings.

**Comment by journeyman** [comment]
@PolarbearDK could you please describe how exactly I should turn on this setting? (I have tabs for "All languages" and it still doesn't work)

**Comment by PolarbearDK** [comment]
You need to set it for "XAML" as these settings override "All languages".

**Comment by journeyman** [comment]
I did, I have Tabs also for Xaml, but when I format xaml with XamlStyler it inserts tabs only until the start of the tag column, the attributes are aligned with spaces for some reason. (Basically just as you described earlier with TextBlock example)

I'm using VS 2015 RTM, could you please confirm that it works for you?

**Comment by PolarbearDK** [comment]
Please re-read my comment from March 14. It describes how this functionality works, and this has not changed.

**Comment by journeyman** [comment]
> The attribute lines are also indented by a TAB, but then XamlStyler uses spaces to ensure that the attribute lines up with the attributes on previous lines.
Yeah, these spaces are causing problems (with PPT mixed tabs feature), I thought if the ticket is closed, then this has been fixed
