### ISSUE TITLE
Fail to compile universal app after saving XAML file

### ISSUE THREAD

**Issue by agilehobo** [NicoVermeir/XamlStyler#43]
You can reproduce with following steps (XamlStyler 1.4.2):

- Get source code from https://github.com/tutsplus/WindowsPhone-UniversalWindowsApp
- Open MainPage.xaml in Hex Clock.Shared then save it
- Build the solution

It's because of XamlStyler moved Canvas.RenderTransform tag between children's of the Canvas.

BTW, is there any way to ignore a partial of the document? I order the elements by intention but XamlStyler reorder them that make my app doesn't work properly.

**Comment by NicoVermeir** [comment]
You can disable the reorder option in the xamlstyler menu

________________________________

**Comment by NicoVermeir** [comment]
works by disabling canvas children reordering
