### ISSUE TITLE
Possible bug in Grid and Canvas element reordering? Or is it just me... :)

### ISSUE THREAD

**Issue by PolarbearDK** [NicoVermeir/XamlStyler#47]
I've recently added support for reordering Setters, and I'm currently working on refactoring all the element reordering code into a separate service class.

This ensures that it will be a breeze to add new reorder functionality in the future ;)

The code is all all done, but the output is NOT identical to the original Grid & Canvas reorder code.
The difference is how whitespace and especially comments are handled (or actually NOT handled) by the current Grid/Canvas reorder code.

My new service assumes that all whitespace/comments "belongs" to the following element. In the original code it seems to belong to the previous element. 

This has this effect:
Given the following snippet
```XML
<Grid>

	<Node1 Grid.Row="2">
	<Node1 Grid.Row="1">
</Grid>
```
With current XamStyler would produce:
```XML
<Grid>

	<Node1 Grid.Row="1">
	<Node1 Grid.Row="2">
</Grid>
```
However the new code would produce:
```XML
<Grid>
	<Node1 Grid.Row="1">

	<Node1 Grid.Row="2">
</Grid>
```
This at first might seem wrong, but if you add a few comments you see the problem:
Given:
```XML
<Grid>

	<!-- Comment for row 2 -->
	<Node1 Grid.Row="2">
	<!-- Comment for row 1 -->
	<Node1 Grid.Row="1">
</Grid>
```
Current XamStyler would produce:
```XML
<Grid>

	<!-- Comment for row 2 -->
	<Node1 Grid.Row="1">
	<Node1 Grid.Row="2">
	<!-- Comment for row 1 -->
</Grid>
```
New code produces:
```XML
<Grid>
	<!-- Comment for row 1 -->
	<Node1 Grid.Row="1">

	<!-- Comment for row 2 -->
	<Node1 Grid.Row="2">
</Grid>
```

I always write comments in XAML before an element so it seems logical that they should "belong" to the following element, but what about whitespaces?
What do you think the correct output from my test snippet should be?

**Comment by NicoVermeir** [comment]
I've kept it just like this. works good enough for me
if others find it not working well, please open up a new issue
