### ISSUE TITLE
Cannot use CDATA sections in ResourceDictionary

### ISSUE THREAD

**Issue by salvis** [NicoVermeir/XamlStyler#48]
Thank you for a very useful tool!

In a [ResourceDictionary](https://msdn.microsoft.com/en-us/library/bb613547%28v=vs.110%29.aspx) it should be possible to use [CDATA sections](http://www.w3schools.com/xml/xml_cdata.asp).

However, if you put a CDATA section inside a string, then XamlStyler removes the &lt;/system:String&gt; end tag, completely breaking the file content.

This is using the current Xaml Styler 1.5 in Visual Studio 2013 Update 4.

The only work-around is to never save the xaml file...

**Comment by PolarbearDK** [comment]
I have a fix for that, but I'm in the middle of a rewrite.

If you want to fix and compile your version yourself:
```C#
        private void ProcessCDATA(XmlReader xmlReader, StringBuilder output)
        {
            // Add the following line
            UpdateParentElementProcessStatus(ContentTypeEnum.SINGLE_LINE_TEXT_ONLY);
            output
                .Append("<![CDATA[")
                .Append(xmlReader.Value)
                .Append("]]>");
        }
```

**Comment by salvis** [comment]
Thank you for the fix, but after reporting I found out that Microsoft doesn't actually support CDATA in XAML as I expected.The way to go is to use `xml:space="preserve"` as documented in

https://msdn.microsoft.com/en-us/library/ms788746%28v=vs.110%29.aspx

**Comment by NicoVermeir** [comment]
going to close this one since another bug has been opened for the preserve stuff
