### ISSUE TITLE
Must not reformat content of elements with xml:space="preserve"

### ISSUE THREAD

**Issue by salvis** [NicoVermeir/XamlStyler#49]
The background of https://github.com/NicoVermeir/XamlStyler/issues/48 is that I would like to have newlines in a string, and I found out that CDATA doesn't actually help with that. (Which does not mean that Xaml Styler is free to break CDATA sections but it lowers the priority of the other issue.)

The way to do it in XAML is to add an `xml:space="preserve"` attribute to the string. However, this raises another issue: Xaml Styler reformats an element like 

       <s:String x:Key="Key" xml:space="preserve">line 1
       line 2</s:String>

to

       <s:String x:Key="Key" xml:space="preserve">
          line 1
          line 2
       </s:String>

Obviously, this is unusable because it results in a string with three newlines instead of just one, and a lot of unwanted spaces, too. The expected behavior is to NOT reformat text (including leading and trailing white space) inside the scope of `xml:space="preserve"`.

Note that `xml:space="preserve"` affects nested elements, too, not just the element containing the attribute.

Again, this is using the current Xaml Styler 1.5 in Visual Studio 2013 Update 4, and the only work-around is to never save the file (or to turn off "beautify on saving").

**Comment by PolarbearDK** [comment]
What namespace is "xml" prefix associated with?

**Comment by salvis** [comment]
Sorry for not replying sooner.

CDATA is not actually working, even if Xaml Styler would leave it alone.

https://msdn.microsoft.com/en-us/library/ms788746%28v=vs.110%29.aspx

calls for using `xml:space=preserve`. That's what I tried to say above.

**Comment by wdsniderman** [comment]
I concur with salvis.  I am having the same issue and it is a real pain.

**Comment by PolarbearDK** [comment]
I have made a beta release available at: 
https://github.com/PolarbearDK/XamlStyler/releases/tag/2.0Beta
