### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by sryze** [NicoVermeir/XamlStyler#51]
I think XamlStyler should have a configuration file where it would read its settings from, perhaps something similar to `.editorconfig` used in [EditorConfig](http://editorconfig.org/) (but I'd vote for YAML instead of ini).  This could be useful for keeping the settings consistent across developers / environments.

**Comment by NicoVermeir** [comment]
similar to #61 
I'm currently not planning on this because of the amount of work it would take vs the advantages it would offer

**Comment by NicoVermeir** [comment]
it was pointed out to me that it's possible to export the XAML styler settings using Visual Studio's import / export settings option. this could serve as a workaround
