### ISSUE TITLE
Max characters per attribute, max characters per line

### ISSUE THREAD

**Issue by antoinebj** [NicoVermeir/XamlStyler#52]
It would be nice to define a maximum number of characters per attribute, and maximum number of characters per line. If any of them is hit, the next attribute will be on the next line.

This allows to keep 2 attributes next to the start tag if they are short enough, instead of relying on a special list of elements which have no line breaks between attributes.

Thanks for your efforts!

**Comment by NicoVermeir** [comment]
Attribute Tolerance and max attribute characters per line settings do this I believe
