### ISSUE TITLE
Escaping of space character is ignored within markup extension

### ISSUE THREAD

**Issue by antoinebj** [NicoVermeir/XamlStyler#53]
`{Binding StringFormat={} {0}\ , Mode=OneWay}` is collapsed into `{Binding StringFormat={} {0}\, Mode=OneWay}`

Note the space after `\` is removed.
It's a good thing that the resulting XAML is invalid though, otherwise some regressions could have gone unnoticed.

**Comment by PolarbearDK** [comment]
I have made a beta release available at: 
https://github.com/PolarbearDK/XamlStyler/releases/tag/2.0Beta
