### ISSUE TITLE
Would it be possible to implement ctrl + m + o for xaml?

### ISSUE THREAD

**Issue by JohanLarsson** [NicoVermeir/XamlStyler#56]
I'm thinking it would be nice to collapse everything to the level the cursor is.
I am aware of ctrl + m + l.

Awesome extension!

**Comment by NicoVermeir** [comment]
Hi Johan,

sorry for the (very) late reply. Could you specify what you mean a bit? I don't quite understand your description

**Comment by JohanLarsson** [comment]
I'm thinking something like:

Say we have:
![image](https://cloud.githubusercontent.com/assets/1640096/14743126/4b9f28ac-08a0-11e6-8e6e-f968aa910a1c.png)

And then do `ctrl + m + o` resulting in:

![image](https://cloud.githubusercontent.com/assets/1640096/14743151/7970538c-08a0-11e6-86d2-345582ac4bc9.png)

I'm thinking collapse all elements of the parent container of where the mouse cursor is.

**Comment by NicoVermeir** [comment]
ah yes, seems like a nice feature. I'll investigate what's possible. it might take some time since this is an entire new feature and I need to look into the VS SDK to see if / how we can do this

**Comment by JohanLarsson** [comment]
Hopefully I'll have time to contribute but can't promise anything as thing are now.

**Comment by NicoVermeir** [comment]
I reopend this at the new repository:
https://github.com/Xavalon/XamlStyler/issues/4

going to close this, since this repository won't be updated anymore
