### ISSUE TITLE
No line breaks in binding attributes

### ISSUE THREAD

**Issue by vfiorin** [NicoVermeir/XamlStyler#57]
Would it be possible to add an option to keep a binding attribute in the same line?

**Comment by amazingant** [comment]
+1, just started trying out this plugin and immediately started getting `RelativeSource` bindings thrown onto three lines with indentation issues as mentioned in #27. Would love a setting to leave make sure each attribute is only on one line. :)

**Comment by NicoVermeir** [comment]
I'm labeling this as a bug because in the new win10 apps, if you use x:Bind and split it over 2 lines it actually gives a compile error (in the beta sdk).

I'll have a look at adding this as an option

**Comment by NicoVermeir** [comment]
added the following options:
- keep Binding on same line (default: false)
- keep x:Bind on same line (default: true)
