### ISSUE TITLE
Reordering Grid and Canvas children can cause functional changes

### ISSUE THREAD

**Issue by RandomEngy** [NicoVermeir/XamlStyler#60]
I think that reordering Grid and Canvas children should be disabled by default, since this can change the z-ordering of the elements. This has caused a number of surprise bugs on our project; so it seems like it should be an opt-in feature.

**Comment by JohanLarsson** [comment]
While I recognize the issue I strongly disagree. Reordering grid children is one of the nicest features of this nice extension ime.

**Comment by RandomEngy** [comment]
It is exposed as a config setting. I'm suggesting that it should be disabled by default, to avoid surprising users with functional changes in the app. I certainly didn't expect a XAML beautification tool to alter the way things look in the app.

**Comment by NicoVermeir** [comment]
I don't really agree. I think if it's disabled by default a lot of people will miss that the option exists. Also, more people will benefit from it than people that will have to switch it off.

**Comment by RandomEngy** [comment]
Okay. Though please take a look at my bug fix pull request!
