### ISSUE TITLE
Setting per project/sln

### ISSUE THREAD

**Issue by JohanLarsson** [NicoVermeir/XamlStyler#61]
I have no idea how this could be implemented but it would be nice to have settings per project and solution like Resharper and StyleCop.
Having different settings in a team creates lots of noise in version control history.

**Comment by NicoVermeir** [comment]
as far as I know this is not possible with the default VS SDK. Resharper uses its own settings implementation, while XAML styler plugs into the VS settings via the SDK.

I'm going to close this for now. should you find a way to do this, feel free to let me know and I'll reopen

**Comment by NicoVermeir** [comment]
it was pointed out to me that it's possible to export the XAML styler settings using Visual Studio's import / export settings option. this could serve as a workaround
