### ISSUE TITLE
Line join groups

### ISSUE THREAD

**Issue by Discrepantia** [NicoVermeir/XamlStyler#62]
It would be great to bring together certain groups.

Make:
Height="100"
Width="50" ScrollViewer.HorizontalScrollBarVisibility="Auto" 
ScrollViewer.VerticalScrollBarVisibility="Auto"

To:
Height="100" Width="50"
ScrollViewer.HorizontalScrollBarVisibility="Auto" ScrollViewer.VerticalScrollBarVisibility="Auto"

**Comment by PolarbearDK** [comment]
This is already supported by XamlStyler.

Configure "Put attributes order rule groups on separate lines" to True, and make sure "Max attribute number per line" is 0 (or a value larger than 2).

Optionally add ScrollViewer.HorizontalScrollBarVisibility ScrollViewer.VerticalScrollBarVisibility to one of the existing attribute groups.
