### ISSUE TITLE
Root Element

### ISSUE THREAD

**Issue by samuelmueller** [NicoVermeir/XamlStyler#67]
I really like the XamlStyler! It helps me a lot in my daily work. 

I've a little Problem with the 'Root element line breaks between attributes' Setting. I've set the value to Always and i'm expecting, that the namespace definitions will be kept on a single line. 

Example: 
The following Window Definition is what i would expect. 
 ```XAML
<Window x:Class="Test.MainWindow"
				xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
				xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
				xmlns:xctk="http://schemas.xceed.com/wpf/xaml/toolkit"
				xmlns:system="clr-namespace:System;assembly=mscorlib"
				Title="MainWindow"
				Height="350"
				Width="525">
	<StackPanel>
```

But if i'm formatting the Xaml I get this:
```XAML
<Window x:Class="MaskedTextBoxTest.MainWindow" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:xctk="http://schemas.xceed.com/wpf/xaml/toolkit"
        xmlns:system="clr-namespace:System;assembly=mscorlib" Title="MainWindow" Height="350" Width="525">
	<StackPanel>
```

When i change the 'Root element line breaks between attributes' to Never then everything is on a single line. 

Could you please check and fix this Issue or explain me what i'm doing wrong :)

**Comment by PolarbearDK** [comment]
That's not what it is supposed to do... and you are doing it correctly.
I know that the previous version was working fine.

The next version has this fixed, but I found another problem related to markup extension formatting. If you change your Title to:
        Title="{Binding Title}"
And reformat, you might get an extra line between Title and Height.

Fixing...

**Comment by PolarbearDK** [comment]
If you are impatient, then build your own from: https://github.com/PolarbearDK/XamlStyler/tree/Root_Attribute_Handling

**Comment by PolarbearDK** [comment]
I have made a beta release available at: 
https://github.com/PolarbearDK/XamlStyler/releases/tag/2.0Beta

**Comment by samuelmueller** [comment]
I've downloaded the beta release and now everything works like expected. 
Thank you very much for your fast fix!
