### ISSUE TITLE
Support Blend for Visual Studio 2015

### ISSUE THREAD

**Issue by sh4nji** [NicoVermeir/XamlStyler#72]
With VS2015 we can now install Extensions in Blend. XAMLStyler is listed but when trying to install it it errors with the following message: "This extension is not supported on the current product."

**Comment by PolarbearDK** [comment]
Where did you find that option?

I have:
Microsoft Blend for Visual Studio Professional 2015
Version 14.0.23107.0 D14REL

But I cant find where to install extensions.

**Comment by sh4nji** [comment]
Blend for Microsoft Visual Studio Enterprise 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.00081

![start page - microsoft blend for visual studio_2015-07-28_15-22-07](https://cloud.githubusercontent.com/assets/362297/8932304/8b9ddbb6-353c-11e5-9c8c-10b2cc917587.png)

**Comment by PolarbearDK** [comment]
Baah! That menu item is missing from Professional version which is what I have access to.

Can't help you there mate.

**Comment by NicoVermeir** [comment]
I've been looking into this but I can't find any documentation on how to add Blend as an install target. if anyone would stumble upon something, please let me know.

**Comment by NicoVermeir** [comment]
Apparently, Microsoft enables Blend support for extensions on a case-by-case bases for now. I'm working with them to see if we can get support for XAML Styler in Blend. I'll keep everyone posted

**Comment by NicoVermeir** [comment]
![image](https://cloud.githubusercontent.com/assets/3177418/14868789/c8e76e90-0ccf-11e6-842e-9a3e01a42082.png)
:)

**Comment by sh4nji** [comment]
Great stuff. Thank you.

**Comment by NicoVermeir** [comment]
fixed in 2.1
