### ISSUE TITLE
In VS2015 the formatter add spaces at the start of comment <!--#region -->

### ISSUE THREAD

**Issue by gigios** [NicoVermeir/XamlStyler#75]
VS2015 add the possibility to define the #region section inside the xaml without the usage of external extension.
The problem is that the VS use the comment  (and ) without any spaces from the '!--' and the #region.
The formatter add two spaces at the comment and the VS is not able to recognize the region section.

**Comment by riwickel** [comment]
fixed in https://github.com/NicoVermeir/XamlStyler/pull/81
