### ISSUE TITLE
Wrong formatting

### ISSUE THREAD

**Issue by stilettk** [NicoVermeir/XamlStyler#76]
I have a VS2015 and max attribute numbers per line is set to 2.

    <Viewbox Margin="{TemplateBinding Padding}" SnapsToDevicePixels="True" Stretch="Uniform">
        <Canvas />
    </Viewbox>
is formatted as
```
<Viewbox Margin="{TemplateBinding Padding}"
         
         SnapsToDevicePixels="True" Stretch="Uniform">
    <Canvas />
</Viewbox>
```
I expect the same result, but without the blank line.

**Comment by chris84948** [comment]
I'm also running into this issue, occasionally it will show reformat with a blank line --

    <Rectangle Width="{Binding RelativeSource={RelativeSource AncestorType=Label},
                                                   Path=ActualWidth}"
                                   Height="{Binding RelativeSource={RelativeSource AncestorType=Label},
                                                    Path=ActualHeight}"
                                   
                                   Fill="Black"
                                   Opacity="0.2" />

I have no idea if this is anything, but it's something I noticed when I went to Visual Studio 2015.

Here are my settings in case that's got anything to do with it --

![image](https://cloud.githubusercontent.com/assets/6255714/12092787/dfb34f5a-b2c4-11e5-9713-d39842269801.png)

**Comment by NicoVermeir** [comment]
I can't reproduce this behavior in 2.0, so I'm assuming this got fixed. Should it still be an issue, feel free to reopen this.
