### ISSUE TITLE
Reordering Canvas and Grid children caused functional change.

### ISSUE THREAD

**Issue by omanuke** [NicoVermeir/XamlStyler#77]
Like https://github.com/NicoVermeir/XamlStyler/issues/60, I think this is issue.
This caused functional change to my application and I can't find who change this order for a while.
The order of children has functional meanings.
In my case,change of order bring some control to front and it hooked some event that should be handled by other control. That control was top most before reorder.

**Comment by NicoVermeir** [comment]
that's an option that reorders grid and canvas children according to their relative positions. it's on by default but can be disabled
