### ISSUE TITLE
[Improvement]Need a way to avoid reorder some of the xaml part

### ISSUE THREAD

**Issue by KiritoStudio** [NicoVermeir/XamlStyler#78]
I want a panel(x:Name=p) to cover the page when Grid(x:Name=root) is the root control of the page, so I must to put it to the bottom of the root. But in this case, if I save the page the XamlStyler will help me to reorder the Grid.Row/Grid.Column and I don't think disable the reorder is a good solution. Could I create some attribute to disable the p for reorder?

**Comment by NicoVermeir** [comment]
that's an option that reorders grid and canvas children according to their relative positions. it's on by default but can be disabled
