### ISSUE TITLE
Problem with "Attribute tolerance" setting

### ISSUE THREAD

**Issue by evilkos** [NicoVermeir/XamlStyler#82]
I have set "Max attribute characters per line" to 130 and I want attributes break to the next line only when the next one will exceed this guide of 130 characters. But I cannot achieve this, because when I set Attribute tolerance to 0 or 1, it puts every attribute on its line; when I set Attribute tolernce to, for example, 8, some lines that have less than 8 attributes exceed 130 characters, but don't break into new lines, and some lines that have more than 8 attributes get broken down in seemingly arbitrary places.

Example. Before beautify:
`<Button TabIndex="98" Content="ОК" IsCancel="True" IsDefault="True" Command="{Binding SaveCommand}" CommandParameter="{Binding RelativeSource={RelativeSource Mode=FindAncestor, AncestorType=Window}}" IsEnabled="{Binding BtnOkEnabled}" Width="80" VerticalAlignment="Bottom" />`

should be 3 lines:
`1: <Button TabIndex="98" Content="ОК" IsCancel="True" IsDefault="True" Command="{Binding SaveCommand}" `
`2:  CommandParameter="{Binding RelativeSource={RelativeSource Mode=FindAncestor, AncestorType=Window}}" `
`3:  IsEnabled="{Binding BtnOkEnabled}" Width="80" VerticalAlignment="Bottom" />`

**Comment by PolarbearDK** [comment]
Markup Extensions are always placed on a new line. 
Could that be an explanation of the behavior you are seeing?

**Comment by NicoVermeir** [comment]
I'm going to close this issue for now. if this is still an issue, please open a new issue at https://github.com/Xavalon/XamlStyler/issues

thank you
