### ISSUE TITLE
Would be nice to be able to reorder groups

### ISSUE THREAD

**Issue by evilkos** [NicoVermeir/XamlStyler#84]
I don't really care about witdths and vertical alignments of the element, I want to see first these ones: Content, Text, ItemsSource, SelectedItem, i.e. something related to business logic, and the styling details should follow last. For now I just included those attributes to group 04 Element name group, but it feels wrong.

**Comment by PolarbearDK** [comment]
This attribute ordering rule groups are 100% customizable In XamlStyler Version 2+.
