### ISSUE TITLE
Setting "Root element line breaks between attributes" = Always - doesn't work

### ISSUE THREAD

**Issue by evilkos** [NicoVermeir/XamlStyler#85]
I'm happy to see this setting, because I really don't like "each attribute on its own line" style, but it is handy on a root element, so it is nice to be able to override just that. But the setting doesn't work, I've set it to "Always" and my attributes are still several a line.

**Comment by PolarbearDK** [comment]
I can't reproduce this. 
Could you please provide an example of this.

**Comment by NicoVermeir** [comment]
I'm going to close this issue for now. if this is still an issue, please open a new issue at https://github.com/Xavalon/XamlStyler/issues

thank you
