### ISSUE TITLE
Prevent moving periods and commas to a new line

### ISSUE THREAD

**Issue by Alex-Butenko** [NicoVermeir/XamlStyler#87]
Before Xaml Styler:
```Xaml
<TextBlock>
  <Hyperlink Click="HyperlinkCheckForUpdates_Click">
    <TextBlock Text="check for updates" />
  </Hyperlink>.
</TextBlock>
```
After Xaml Styler:
```Xaml
<TextBlock>
  <Hyperlink Click="HyperlinkCheckForUpdates_Click">
    <TextBlock Text="check for updates" />
  </Hyperlink>
  .
</TextBlock>
```
It moves ending period to a new line and I can't find any setting to prevent it.Otherwise took is amazing but this behavior makes the extension unusable, because it changes the look of the result:
`check for updates.` vs `check for updates .`

**Comment by NicoVermeir** [comment]
add xml:space="preserve" to your page, that prevents this behavior
