### ISSUE TITLE
Xaml Styler is not enable for a Xaml page in xamarin

### ISSUE THREAD

**Issue by SyntaxThemes** [NicoVermeir/XamlStyler#91]
Hi Nico

This is an awesome extension!! I am using Xaml pages in the Xamarin extension for visual studio.  I automatically tried to clean the Xaml style using your extension but it didn't work on this type of page.  However it still works in standard WPF pages.

Not working on Cross-Platform -> Forms Xaml Page (From the Add New Templates)

How can I fix this?

Thanks you very much!!

**Comment by NicoVermeir** [comment]
hey,

it should work as far as I know. I'm currently installing the extensibility tools for VS and I'm planning to better maintain / update this extension. give me some time to setup my environment again, verify the current pull requests and I'll have a look at it then.

thanks :)

**Comment by NicoVermeir** [comment]
been working in Forms all day yesterday, the extension seemed to work perfectly. I'll close this for now, feel free to open a new bug if this persists
