### ISSUE TITLE
Suggestions for milestone 2.0

### ISSUE THREAD

**Issue by PolarbearDK** [NicoVermeir/XamlStyler#92]
Hi Nico! Welcome back.

I had all but given up on this project.
What are your plans for milestone 2.0?

I had some changes in the pipeline, but lost momentum when there was no response to my pull requests.

I was working on a proper MarkupExtension Parser based on Irony (https://irony.codeplex.com/).

I also have an idea on how to fix the mixed tab/spaces issue.

**Comment by JohanLarsson** [comment]
What about moving this project to an organization and add a couple of members?
That way it will not rely on one person not being busy.

**Comment by NicoVermeir** [comment]
I'd love to discuss this, maybe take the discussion offline for a bit? drop me an email nico_vermeir@hotmail.com and we'll discuss the future of this extension :)
