### ISSUE TITLE
Update to 2.0 breaks on VS2013

### ISSUE THREAD

**Issue by robsmithx** [NicoVermeir/XamlStyler#96]
Hi,

I updated to V2.0 on Visual Studio 2013, and Xaml Styler will no longer load. In the activity log I get:

    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [StylerPackage]</description>
    <guid>{A224BE3C-88D1-4A57-9804-181DBEF68021}</guid>
    <hr>80070002</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.12.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Comment by NicoVermeir** [comment]
sorry to hear that. I'm installing VS2013 as we speak, will try to fix it ASAP

**Comment by NicoVermeir** [comment]
hmm I just tried it, seems to work fine. I tested on VS2013 Ultimate with update 5.
What version are you using?

**Comment by robsmithx** [comment]
Microsoft Visual Studio Professional 2013 Version 12.0.40629.00 Update 5

Xaml Styler is trying to load "Microsoft.VisualStudio.Shell.12.0, Version=14.0.0.0". Isn't this the VS2015 version i.e. won't be present if I only have VS2013?

**Comment by drehren** [comment]
Indeed... The extension will load in VS2013 only if VS2015 is installed... it happened to me a while ago with other extension...

**Comment by NicoVermeir** [comment]
I've indeed reproduced the issue. I'm looking into it

**Comment by NicoVermeir** [comment]
apparently, it's fixed if you generate a vsix while having the VS2013 SDK installed. We're going to put a few more fixes in and release 2.1 in the coming days, I'll close this issue once it's released so you'll get notified

**Comment by robsmithx** [comment]
OK, thanks for this.

**Comment by NicoVermeir** [comment]
fixed in 2.1
